### ISSUE TITLE
Problems with executing LSP commands

### ISSUE THREAD

**Issue by drzbida** [Saghen/blink.cmp#1219]
### Make sure you have done the following

- [x] Updated to the latest version of `blink.cmp`
- [x] Searched for existing issues and documentation (try `<C-k>` on https://cmp.saghen.dev)

### Bug Description

Related to the recently added https://github.com/Saghen/blink.cmp/pull/1130

_Context:_

There are some LSPs that give you a completion item with a command to execute for the completion to work, same story as https://github.com/Saghen/blink.cmp/issues/1148#issuecomment-2634545246 :). Well, that's actually not even the full story. In this exact case mentioned before, the server actually gives you the name of the **client** command that needs to be executed and is implemented by the [..client](https://github.com/dotnet/vscode-csharp/blob/3afe7b55d26bd7dadf957f1e6a37c7fe00654fb9/src/lsptoolshost/server/serverCommands.ts#L77). This can be done in neovim by setting `vim.lsp.commands[COMMAND_NAME]` like in this [example](https://github.com/seblyng/roslyn.nvim/blob/63b0c30bb6b82b1f5b100cde3a212a5a3a677869/lua/roslyn/lsp_commands.lua#L58). The vscode implementation needs to be replicated in `roslyn.nvim` for override completions to work.

_Problem 1:_

Neovim does not check every workspace/executeCommand request for a client implementation, but only those originating from specific parts of the core code. I wrote more about this in a [neovim issue](https://github.com/neovim/neovim/issues/32406), but only the new neovim 0.11 completion was fixed and I think it's up for each completion plugin to check for client implementations before calling executeCommand themselves. I've started working on adding this functionality in blink.cmp, but I got stuck with the following issue

_Problem 2:_ (FIXED & Tested that the resolved command arrives)

The `item` that arrives in `lsp:execute` is incomplete. In my case, the `item` that I have after `completionItem/resolve` contains the `command` parameter, while the item I get in `lsp:execute` does not. This is a problem even without considering implementing the previous issue. Example:

This is my [transformed_item](https://github.com/Saghen/blink.cmp/blob/9e95af47ea25d396405a67d5b298446959f3e4b9/lua/blink/cmp/sources/lib/provider/init.lua#L147) which contains the command:
```
{
  client_id = 1,
  client_name = "roslyn",
  command = {
    arguments = { {
        uri = "redacted"
      }, {
        newText = "rocess(double delta)\r\n    {\r\n        base._Process(delta);\r\n    }",
        range = {
          ["end"] = {
            character = 27,
            line = 30
          },
          start = {
            character = 27,
            line = 30
          }
        }
      }, false, 1001 },
    command = "roslyn.client.completionComplexEdit",
    title = "CompleteComplexEditCommand"
  },
  commitCharacters = { "(" },
  cursor_column = 27,
  data = {
    ResultId = 17,
    TextDocument = {
      uri = "redacted"
    }
  },
  documentation = {
    kind = "markdown",
    value = "```csharp\r\nvoid Node._Process(double delta)\r\n```\r\n  \r\nCalled during the processing step of the main loop\\. Processing happens at every frame and as fast as possible, so the&nbsp;delta&nbsp;time since the previous frame is not constant\\.&nbsp;delta&nbsp;is in seconds\\.  \r\n  \r\nIt is only called if processing is enabled, which is done automatically if this method is overridden, and can be toggled with&nbsp;Node\\.SetProcess\\(bool\\)\\.  \r\n  \r\nCorresponds to the&nbsp;Node\\.NotificationProcess&nbsp;notification in&nbsp;GodotObject\\.\\_Notification\\(int\\)\\.  \r\n  \r\n**Note:**&nbsp;This method is only called if the node is present in the scene tree \\(i\\.e\\. if it's not an orphan\\)\\."
  },
  exact = false,
  filterText = "_Process",
  insertTextFormat = 1,
  insertTextMode = 1,
  kind = 2,
  label = "_Process(double delta)",
  score = 26,
  score_offset = 0,
  sortText = "_Process",
  source_id = "lsp",
  source_name = "LSP",
  textEdit = {
    newText = "_P",
    range = {
      ["end"] = {
        character = 27,
        line = 30
      },
      start = {
        character = 25,
        line = 30
      }
    }
  },
  textEditText = "_P"
}
```

This is my [item ](https://github.com/Saghen/blink.cmp/blob/9e95af47ea25d396405a67d5b298446959f3e4b9/lua/blink/cmp/sources/lsp/init.lua#L161C17-L161C21) which does not contain the command

```
{
  client_id = 1,
  client_name = "roslyn",
  commitCharacters = { "(" },
  cursor_column = 27,
  data = {
    ResultId = 17,
    TextDocument = {
      uri = "redacted"
    }
  },
  exact = false,
  filterText = "_Process",
  insertTextFormat = 1,
  insertTextMode = 1,
  kind = 2,
  label = "_Process(double delta)",
  score = 26,
  score_offset = 0,
  sortText = "_Process",
  source_id = "lsp",
  source_name = "LSP",
  textEdit = {
    newText = "_P",
    range = {
      ["end"] = {
        character = 27,
        line = 30
      },
      start = {
        character = 25,
        line = 30
      }
    }
  },
  textEditText = "_P"
}
```

P.S: I've just migrated from a "bloated" nvim-cmp configuration and I can't believe how much faster it feels and how fast it was to migrate everything :). Thank you for your work.

### Relevant configuration

```lua

```

### `neovim` version

NVIM v0.11.0-dev-1756+gc091bc3b9a

### `blink.cmp` version

v0.11.0

**Comment by Saghen** [comment]
I'm really happy it's working well for you :) I've just pushed a fix that should pass the resolved item to the execute

**Comment by drzbida** [comment]
Thank you for the help :) 

I've [added](https://github.com/drzbida/blink.cmp/compare/main...complete-commands) the call to custom client commands and skipping brackets for items with a command that needs to be executed (as either the custom command or the LSP command will complete the item), but I still have a problem with the resolved item. It seems that the item is still not complete (misses the command) *only for the first item that has a command*. This happens for the first accepted item with a command like 4 out of 5 times. After that, the item always contains the command and works. It still works after changing buffers. I've checked that the item is indeed resolved in general and contains the command (the transformed_item has it). Do you have any hunch as to why that might be the case? 

Showcase example in case it's not clear what I mean:

https://github.com/user-attachments/assets/c2e2a18e-2af7-4837-a22a-2d803f94170e

**Comment by Saghen** [comment]
Rather than skipping the auto brackets if the item contains a command, we should allow sources to opt-out of auto brackets, and add a `lsp/hacks/your-lsp.lua` which disables it for this LSP. Generally speaking, LSPs add auto brackets as part of `resolve` or return it in the original `get_completions` response, so this should be a pretty rare case

**Comment by drzbida** [comment]
> Would also be good to add a note to the code about dropping the client implementation check on the command when we switch to supporting only v0.11+

It seems we can just use exec_cmd from lsp client instead of manually sending the lsp request. This one does the check. It was available in <0.11 as a "private" method (although it was already used in other parts of core neovim as a public api). Execute could look something like this if it's acceptable, I've seen there are other places in the codebase which check the neovim version. 

```lua
function lsp:execute(source, item, callback)
  local client = vim.lsp.get_client_by_id(item.client_id)
  local command_data = item.command

  if not (client and command_data) then
    callback()
    return
  end

  if vim.fn.has('nvim-0.11') == 1 then
    client:exec_cmd(command_data, { bufnr = source.bufnr }, function() callback() end)
  else
    -- TODO: remove this once 0.11 is the minimum version
    client:_exec_cmd(command_data, { bufnr = source.bufnr }, function() callback() end)
  end
end
```


> Rather than skipping the auto brackets if the item contains a command, we should allow sources to opt-out of auto brackets, and add a lsp/hacks/your-lsp.lua which disables it for this LSP. Generally speaking, LSPs add auto brackets as part of resolve or return it in the original get_completions response, so this should be a pretty rare case

I'm not sure what you mean, do you mean disabling the brackets for the LSP in general? Because in the case for Roslyn the server doesn't actually complete the brackets. This was needed because when using autobrackets and you want to accept the a completion like:

```csharp
public override void _Dro // accept _DropData(Vector2 atPosition, Variant data)
```

The command executes and it becomes
```csharp
public override void _DropData(Vector2 atPosition, Variant data)
{
    base._DropData(atPosition, data);
}() // extra brackets here
```

For normal scenarios, the autobrackets added are needed. The LSP specs indeed says `additional modifications to the current document should be described with the additionalTextEdits-property`, so what happens here is out of spec. I don't honestly know any other lsp which uses commands in completion to see what they do with it, so we can definitely move the hack for the brackets in the roslyn plugin as to not bloat this.

**Comment by disrupted** [comment]
Is this related? https://github.com/neovim/neovim/commit/f20335a54ce7f240902d4ee14d726620a38f95bc This feature was just merged into Neovim core.
