### ISSUE TITLE
Fuzzy/Sorting Mega issue

### ISSUE THREAD

**Issue by magnusriga** [Saghen/blink.cmp#1642]
## Note from Saghen

Please feel free to post any of your undesirable sorting behaviors below! Please try setting `fuzzy.use_frecency/use_proximity = false` before posting and ensure you're on the latest version.

---

### Make sure you have done the following

- [x] Updated to the latest version of `blink.cmp`
- [x] Searched for existing issues and documentation (try `<C-k>` on https://cmp.saghen.dev)

### Bug Description

Opening the completion menu in vscode / cursor in a Typescript file gives:

<img width="504" alt="Image" src="https://github.com/user-attachments/assets/7259d3dd-2c3c-4380-9955-49b0f0e5730d" />

In Neovim with `blink.cmp`, it looks like this:

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/8d50a176-8b3f-4c30-b41e-ad1d1fa7b763" />

In a browser DevTools console, the order matches vscode.

I am trying to get `blink.cmp` to match the vscode order, which through testing looks like it should be:

1.  Lowercase - Local
2.  Lowercase - Remote (must be imported)
3.  Emmets
4.  Snippets
5.  Lowercase - Local, deprecated
6.  Lowercase - Remote, deprecated

7.  Uppercase - Local
8.  Uppercase - Remote
9.  Uppercase - Local, deprecated
10. Uppercase - Remote, deprecated

I currently have the following sort order set:

```lua
        sorts = {
          -- Always prioritize exact matches, case-sensitive.
          "exact",

          -- Sort by Fuzzy matching score.
          "score",

          -- Sort by `sortText` field from LSP server, defaults to `label`.
          -- `sortText` often differs from `label`.
          "sort_text",

          -- Sort by `label` field from LSP server, i.e. name in completion menu.
          -- Needed to sort results from LSP server by `label`,
          -- even though protocol specifies default value of `sortText` is `label`.
          "label",
        },
```

For some reason, `blink.cmp` shows matches that does not start with `c`, before those that do. That is despite having `exact` specified.

Moreover, the upper/lower case order is also not considered in the same way as vscode.

**PS**: I am using LSP `vtsls`, which should match the one used by vscode.

Any idea what I am doing wrong?

### Relevant configuration

```lua
sources = {
  default = { "lsp", "path", "snippets", "buffer" },
}

```

### `neovim` version

NVIM v0.12.0-dev-132+gee3f9a1e03

### `blink.cmp` version

main

**Comment by Saghen** [comment]
The exact match is for when you've typed "foo" matching against "foo", not for when you've typed "foo" matching against "foobar".

Making the label sort prioritize lowercase over capitals makes sense to me. It's possible that `_C` incorrectly receives a double bonus (delimiter and camelCase bonuses, should just receive delimiter bonus) in the fuzzy matcher which is why it's so prominent, but I'll need to look into it

**Comment by magnusriga** [comment]
Thanks @Saghen , just let me know if I can help test further.

**Comment by jjiangweilan** [comment]
> The exact match is for when you've typed "foo" matching against "foo", not for when you've typed "foo" matching against "foobar".
> 
> Making the label sort prioritize lowercase over capitals makes sense to me. It's possible that `_C` incorrectly receives a double bonus (delimiter and camelCase bonuses, should just receive delimiter bonus) in the fuzzy matcher which is why it's so prominent, but I'll need to look into it

I am also very confused by the behaviour of exact match
```
// config
fuzzy = {
    sorts = {
        'exact',
        'score',
        'sort_text',
    },
},
```

![Image](https://github.com/user-attachments/assets/7ec9b038-c2ae-4a0f-8353-cb3307e15ba7)

**Comment by magnusriga** [comment]
@jjiangweilan I think we can conclude, as @Saghen said, that the issue is with `_<char>` being given too much weight, under the hood.

**Comment by Saghen** [comment]
Yep, working on it in https://github.com/Saghen/frizbee/pull/28

**Comment by magnusriga** [comment]
@Saghen  Not sure if this is related, but check out this odd sorting, after setting sorting to label only (`sorts = { 'label' }`):

![Image](https://github.com/user-attachments/assets/d7817e5b-4cd9-46b5-8c12-1d3aa9b2caa0)

It starts out with snippets, then shows two entries that seem completely misplaced, then it starts showing the right entries (`Netw...`).

Any idea what is going on here?

**Comment by magnusriga** [comment]
@Saghen Both `lua` and `rust` give the wrong order, each in their own unique ways:

**With `implementation = "lua"`**:
* Order is non-deterministic. Around 50% of the time, in a TS file, snippets all show up at the top of the completion list.

**With `implementation = "prefer_rust_with_warning"`**:
* Wrong fuzzy matching of notes, e.g. searching for “dock” shows “Docker” further down than “Foo, Bar, Docker”.
* Often shows external packages and google fonts first, before matching start snippets.
* Non-deterministic, sometimes the list starts with uppercase entries, other times with lowercase.
* Snippets are never at the top, as expected.

**Comment by Saghen** [comment]
The incorrect double bonus on `_C` was resolved by https://github.com/Saghen/blink.cmp/commit/c3a54218bc799bd497db4fb7132d60b14b31707a

**Comment by Heradar** [comment]
> If we start writing an "H", it is likely we want to get an item that starts on "H", not an item with H in the middle.

I think it'd be great if `blink.cmp.CompletionItem` had an `offset` field for the first character index that got matched  to support a sorter like nvim-cmp has [here](https://github.com/hrsh7th/nvim-cmp/blob/b5311ab3ed9c846b585c0c15b7559be131ec4be9/lua/cmp/config/compare.lua#L19)

 It's the second sorter I use below `exact` with nvim-cmp, it's the only think stopping me from switching because matches like this annoy me too much

<img width="391" alt="Image" src="https://github.com/user-attachments/assets/bfbf731f-430e-4d73-be58-b172e574c64d" />

**Comment by jjiangweilan** [comment]
> > If we start writing an "H", it is likely we want to get an item that starts on "H", not an item with H in the middle.
> 
> I think it'd be great if `blink.cmp.CompletionItem` had an `offset` field for the first character index that got matched to support a sorter like nvim-cmp has [here](https://github.com/hrsh7th/nvim-cmp/blob/b5311ab3ed9c846b585c0c15b7559be131ec4be9/lua/cmp/config/compare.lua#L19)
> 
> It's the second sorter I use below `exact` with nvim-cmp, it's the only think stopping me from switching because matches like this annoy me too much
> 
> <img alt="Image" width="391" src="https://private-user-images.githubusercontent.com/44797050/442381541-bfbf731f-430e-4d73-be58-b172e574c64d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4NjUzMzMsIm5iZiI6MTc0Njg2NTAzMywicGF0aCI6Ii80NDc5NzA1MC80NDIzODE1NDEtYmZiZjczMWYtNDMwZS00ZDczLWJlNTgtYjE3MmU1NzRjNjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTEwVDA4MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDUwYzJjODM1Njc0NTVmMDAxMDk2YmVkNTFiODAzOTk4ODRiNjhiZDExY2E3MWQ1MTAyYzYxNzJhZWY0ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rcDgvmx7C8EPs9p77P_CRtlm20EakTIQbXrBfLcA3Hk">

This kinda bothers me too. I guess 'exact' means it's also case senstive. But I wish it can be smart case sensitive. There is a relatived feature requst issue https://github.com/Saghen/blink.cmp/issues/1158

**Comment by jjiangweilan** [comment]
![Image](https://github.com/user-attachments/assets/aa8b157b-71ba-4e99-93f8-60bde49b6a55)
Still having this issue after upgrading to 1.2. I believel it's the `:` this time.

**Comment by Saghen** [comment]
https://github.com/Saghen/blink.cmp/issues/1642#issuecomment-2867111308

Looks like `vtsls` sends the item as `.outerHeight` and `.Highlight` which is quite unusual and breaks the prefix bonus (since `H` ends up being the second character, not the first, in `.Highlight`). I'd like to workaround this by ignoring non-alphanumeric characters in frizbee when calculating the prefix bonus but it's non trivial.

https://github.com/Saghen/blink.cmp/issues/1642#issuecomment-2868525843
https://github.com/Saghen/blink.cmp/issues/1642#issuecomment-2868903691

Both of these would be solved by a bonus for matching on continuous characters, which is also non-trivial to implement unfortunately. We could increase the gap penalty but that may lead to #1598 showing up again

**Comment by toupeira** [comment]
I got a weird issue: I have a folder `/slack` and a file `/swapfile`, and completing `/sl` in the cmdline selects `/swapfile` instead of the expected `/slack`.

The weird part is that it works correctly in a buffer with the `path` source, and none of these settings make a difference:

```lua
    fuzzy = {
      sorts = { 'exact', 'score', 'sort_text' },
      use_frecency = false,
      use_proximity = false,
      max_typos = function() return 0 end,
    },
```

But with `implementation = 'lua'` it works correctly, i.e. `/slack` is completed in the cmdline too.

**Comment by millerjason** [comment]
I've converted to `blink.cmp` recently and overall thrilled with the speed, reliability, and ability to tweak it.  I'm never going back, this module a huge step forward (thank you!).

That said, the matcher is still driving me mildly mad.  In short, I strongly want it to use exact prefix matching above all the other fuzzy rules.  Most of the time I know what I want and just need it to save keystrokes, not try to be creative.

Two items are important to me:

_Item 1_: `PREFIX_BOUNS`

From my experiences over a week, `PREFIX_BONUS` is way to low for my taste.  I ended up monkeypatching this bonus to 12 in my local nvim and that was a game changer for me.  I am happy with my patch, but exposing these bonus values would be great.

With this adjustment 99% of the _code matches_ are what I'd consider reasonable.

_Item 2_: Path matching

I'm still misconfigured or confused how the matching works for paths in cmdline mode.

My relevant settings (although I've tried less complex as well as use frecency/proximity, I'm okay to change them but want to keep with Lua given the moneypatch for item 1):
```
        completion = {
          menu = { auto_show = true },
          list = {
            selection = {
              preselect = true,
              auto_insert = true,
            },
          },
        },
      },
      fuzzy = {
        implementation = 'lua',
        sorts = { 'exact', 'score', 'sort_text' },
        use_frecency = false,
        use_proximity = false,
        max_typos = function()
          return 0
        end,
      },
```

The behavior that I'm seeing (as best I can tell) is that the needle for the match is using the text from the current directory (i.e. the filename ignoring the base path).  At least in lua, it looks like that is being matched with haystack options that are the full paths (so including the base path).  Is that the underlying implementation?  It feels like these should be consistent.

<img width="615" alt="Image" src="https://github.com/user-attachments/assets/7cf50356-b6e0-4746-96d4-5f1c4d2561f6" />

Here I'd want `init.lua` as the most likely choice.  But the `ini` matches are occurring on the common base path rather than items in the current directory.

**Comment by saghen** [comment]
Really appreciate it @millerjason!  The path matching issue should be fixed as of https://github.com/Saghen/blink.cmp/commit/5cf9a786622764f4a8b90735c44e12009ae2e9fc

I'm curious about the `PREFIX_BONUS` change you mentioned, as `12` is [the default in frizbee](https://github.com/Saghen/frizbee/blob/main/src/const.rs#L6), do you mind elaborating on that? It was however set to `6` before [this change](https://github.com/Saghen/frizbee/commit/44482c36f35ef6e60fff4837cb6a4d449efbabd8#diff-65cbcee0380a3e50c18c444534aaa9f226eaaf84d5a83dfb802ad766d408db3eL15)

Edit: Sorry, just re-read and realized youre using the Lua matcher

The main issue with the scoring I've noticed is that `foo` matches with a higher score on `f_o_o` than on `foo`. I'm currently using a locally built version with the `GAP_OPEN_PENALTY = 5` and `DELIMITER/CAPITAL_BONUS = 4` rather than the previous `3` and `8`, which prioritizes `foo` over `f_o_o`. I'll likely make this the default in the next version.

**Comment by saghen** [comment]
I've opened a PR that should fix the last issue I mentioned above. Do you mind giving it a shot and seeing if the behavior works better for you? I have to run so I admittedly haven't tested the lua gap penalty change. I'd be particularly interested in knowing which cases were fixed by increasing the prefix bonus on your end.

**Comment by jjiangweilan** [comment]
> I've opened a PR that should fix the last issue I mentioned above. Do you mind giving it a shot and seeing if the behavior works better for you? I have to run so I admittedly haven't tested the lua gap penalty change. I'd be particularly interested in knowing which cases were fixed by increasing the prefix bonus on your end.

using the fuzzy-scoring branch, I am getting ../lazy/blink/lua/blink/cmp/fuzzy/lua/match.lua:76: fbb should match barbazfoobarbaz with score 18 assertion error

**Comment by millerjason** [comment]
> I've opened a PR that should fix the last issue I mentioned above. Do you mind giving it a shot and seeing if the behavior works better for you? I have to run so I admittedly haven't tested the lua gap penalty change. I'd be particularly interested in knowing which cases were fixed by increasing the prefix bonus on your end.

Thank you, @Saghen.

I am seeing the same error as @jjiangweilan.  But even if I comment out all of the assert tests, that branch still exhibits the same undesirable behavior for path matches.  Confusingly, if I go the the latest `main` branch things work much better now.  Did you tackle this in `2c3d276` ?

**Comment by TomJo2000** [comment]
> I've converted to `blink.cmp` recently and overall thrilled with the speed, reliability, and ability to tweak it. I'm never going back, this module a huge step forward (thank you!).
> 
> That said, the matcher is still driving me mildly mad. In short, I strongly want it to use exact prefix matching above all the other fuzzy rules. Most of the time I know what I want and just need it to save keystrokes, not try to be creative.

Hi, I'm sorry if I'm just adding noise to this thread but this matches my experience switching to `blink.cmp` closely.

I'm overall very happy with the performance and ease of configuration,
but the suggestions, especially for the `cmdline` have been a little counterintuitive out of the box.

As an example when I type in `:La<Tab>` I get `abclear` back as the first result, where I would expect `Lazy`.
I have been able to get it to mostly do what I expect through trial and error now.

> Two items are important to me:
> 
> _Item 1_: `PREFIX_BOUNS`
> 
> From my experiences over a week, `PREFIX_BONUS` is way to low for my taste. I ended up monkeypatching this bonus to 12 in my local nvim and that was a game changer for me. I am happy with my patch, but exposing these bonus values would be great.
> 
> With this adjustment 99% of the _code matches_ are what I'd consider reasonable.
> 
> _Item 2_: Path matching
> 
> I'm still misconfigured or confused how the matching works for paths in cmdline mode.
> 
> My relevant settings (although I've tried less complex as well as use frecency/proximity, I'm okay to change them but want to keep with Lua given the moneypatch for item 1):
> 
> ```
>         completion = {
>           menu = { auto_show = true },
>           list = {
>             selection = {
>               preselect = true,
>               auto_insert = true,
>             },
>           },
>         },
>       },
>       fuzzy = {
>         implementation = 'lua',
>         sorts = { 'exact', 'score', 'sort_text' },
>         use_frecency = false,
>         use_proximity = false,
>         max_typos = function()
>           return 0
>         end,
>       },
> ```

This in particular has been very useful to get the completion behavior more in line with how I expected it to work out of the box.
Although I haven't looked into monkeypatching the `PREFIX_BONUS` yet.

**Comment by millerjason** [comment]
> > I've converted to `blink.cmp` recently and overall thrilled with the speed, reliability, and ability to tweak it. I'm never going back, this module a huge step forward (thank you!).
> > That said, the matcher is still driving me mildly mad. In short, I strongly want it to use exact prefix matching above all the other fuzzy rules. Most of the time I know what I want and just need it to save keystrokes, not try to be creative.
> 
...
> 
> This in particular has been very useful to get the completion behavior more in line with how I expected it to work out of the box. Although I haven't looked into monkeypatching the `PREFIX_BONUS` yet.

FWIW, with the recently merged fixes I was able to give up on all my edits and monkey patches.  Now I'm just using this version (Lua variant) and it works great, even in `cmdline` mode:

```
    'saghen/blink.cmp',
    version = 'v1.*',
    branch = 'main',
    commit = '2c3d276',
```

Thanks for all the quick fixes @Saghen !

**Comment by fin-w** [comment]
<img width="726" height="241" alt="Image" src="https://github.com/user-attachments/assets/6f4d3cff-e836-4216-a8c6-e6461c2ae848" />

I don't feel the `m` should match twice, and certainly the `a` shouldn't match. Looks like the `a` is matching instead / as a substitute of the `_`? 

```lua
    fuzzy = {
        implementation = 'prefer_rust_with_warning',
        sorts = {
            'score',
            'sort_text',
        },
        max_typos = 0,
    }
```

**neovim version**

NVIM v0.12.0-dev-cf5506f0fd
Build type: RelWithDebInfo
LuaJIT 2.1.1744317938

**blink.cmp version**

v1.4.1

**Comment by chancez** [comment]
I'm wondering if it's possible to disable or configure fuzzy matching conditionally, or more specifically: only in `cmdline`. I really like the fuzzy matching for cmdline in many cases, but it doesn't super work well for `/` when there isn't a match for what I'm looking for.

Like I might be doing `/logging` and then the blink autocomplete menu only has `toggling` and with my enter key mapped to `accept_and_enter`, it searches for something different than I originally intended. Like, if I could fuzzy match on prefix only for `cmdline` that would almost be perfect.

**Comment by saghen** [comment]
You can follow the progress on prefix matching in #1258 @chancez

**Comment by saghen** [comment]
Going to close this issue as I believe the big fuzzy matching issues have been fixed by this point. Remaining issues can be in their own issues with the `fuzzy` label
